[[redirects]]
  from = "https://videogamescenter.netlify.app/homepage"
  to = "https://api.igdb.com/v4/multiquery"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
