[[redirects]]
  //from = "/*"
  //to = "/index.html"
  from = "/api/*"
  to = "https://api.igdb.com/:splat"
  status = 200
  force = true
[[headers]]
  for = "/Videogames-project/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
